#! /bin/bash

DIR=$1;

#Scaneia diretórios e subdiretórios
SCAN_DIR_LEVEL_01=`(ls ${DIR}/*html)`;
SCAN_DIR_LEVEL_02=`(ls ${DIR}/**/*html)`;
SCAN_DIR_LEVEL_03=`(ls ${DIR}/**/**/*html)`;

#Altera arquivos HTML
REGEX_REMOVE_JS_FOOTER='s/<\/footer.*/<\/footer>/';
REGEX_REMOVE_DIV_NUXT='s/<div id="__nuxt">/\n/';
REGEX_REMOVE_JS01='/<link rel="modulepreload".*>/d';
REGEX_REMOVE_JS02='s/<script.*module.*><\/script>/\n/';
REGEX_REMOVE_JS03='/<link rel="prefetch" as="script"/d';

#Exclui arquivos de payload que não são mais necessários
SCAN_FILE_LEVEL_01=`(ls ${DIR}/_payload.js)`;
SCAN_FILE_LEVEL_02=`(ls ${DIR}/**/_payload.js)`;
SCAN_FILE_LEVEL_03=`(ls ${DIR}/**/**/_payload.js)`;

echo "" > remove-js-not-used.log;

remove_script_js_head_html(){
    for file in $1; 
       do
        echo $file >> remove-js-not-used.log;
        sed -i -e \
        "$REGEX_REMOVE_DIV_NUXT" -e \
        "$REGEX_REMOVE_JS01" -e \
        "$REGEX_REMOVE_JS02" -e \
        "$REGEX_REMOVE_JS03" -e \
        "$REGEX_REMOVE_JS_FOOTER" $PWD/$file;
    done
};

rm -rf $SCAN_FILE_LEVEL_01;
rm -rf $SCAN_FILE_LEVEL_02;
rm -rf $SCAN_FILE_LEVEL_03;

remove_script_js_head_html "$SCAN_DIR_LEVEL_01";
remove_script_js_head_html "$SCAN_DIR_LEVEL_02";
remove_script_js_head_html "$SCAN_DIR_LEVEL_03";

echo "------------------------------------------------";
echo "";
echo "$(tput setaf 2)Foram removidos javascript nas seguintes páginas:$(tput sgr0)";
cat remove-js-not-used.log;
echo "";
echo "------------------------------------------------";